trigger:
- main  # Replace 'main' with the branch you want to trigger the build from

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndPublishChart
  displayName: 'Build and Publish Helm Chart'
  steps:
  - checkout: self

  # Install Helm
  - task: UseHelm@0
    inputs:
      version: 'latest'
      checkLatest: true

  # Package Helm Chart
  - task: HelmInstaller@1
    inputs:
      helmVersionToInstall: 'latest'

  - script: |
      helm package ./path/to/your/helm/chart
      mkdir -p $(Build.ArtifactStagingDirectory)/charts
      mv *.tgz $(Build.ArtifactStagingDirectory)/charts
    displayName: 'Package Helm Chart'

  # Publish Helm Chart as artifact
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Helm Chart Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/charts'
      ArtifactName: 'helm-chart'
      publishLocation: 'Container'

